export type LeadingSafeQuestion = {
  id: number;
  question: string;
  options: string[];
  correctIndex: number;
};

export const LEADING_SAFE_QUESTIONS: LeadingSafeQuestion[] = [
  { id: 1, question: "What is one example of differentiating business objectives?", options: ["Solution Intent", "Enterprise Goals", "Strategic Themes", "Portfolio Vision"], correctIndex: 2 },
  { id: 2, question: "What is \"precisely specify value by product\" central to?", options: ["SAFe Principles", "SAFe Core Values", "Lean Thinking", "Agile Manifesto"], correctIndex: 2 },
  { id: 3, question: "During the final plan review, ART PI risks are ROAM'ed. What do the letters in ROAM represent?", options: ["Resolved, Owned, Assigned, Mitigated", "Resolved, Owned, Accepted, Mitigated", "Resolved, Owned, Active, Mitigated", "Resolved, Owned, Approved, Mitigated"], correctIndex: 1 },
  { id: 4, question: "What is the focus of Lean Thinking?", options: ["Ensuring respect for people and culture", "Reducing delays", "Moving to an iterative development process", "Implementing objective measures of progress"], correctIndex: 1 },
  { id: 5, question: "Which statement is a value from the Agile Manifesto?", options: ["Customer collaboration over following a plan", "Apply systems thinking", "Individuals and interactions over processes and tools", "Customer collaboration over a constant indefinite pace"], correctIndex: 2 },
  { id: 6, question: "What else does the SAFe principle \"unlock the intrinsic motivation of knowledge workers\" require besides purpose and minimum constraints?", options: ["Incentive-based compensation", "Innovation", "Transparency", "Autonomy"], correctIndex: 3 },
  { id: 7, question: "The primary goal of SAFe is to achieve what?", options: ["Lean Portfolio Management", "Business Agility", "Customer centricity", "Organizing around value"], correctIndex: 1 },
  { id: 8, question: "Restoring the speed and innovation of the entrepreneurial network while leveraging the stability of the hierarchical system is a benefit of what?", options: ["Dual operating system", "Functional silos", "Continuous learning culture", "Customer centricity"], correctIndex: 0 },
  { id: 9, question: "Which statement is true about batch size?", options: ["The handoff batch should be made as large as possible", "When stories are broken into tasks, it means there are small batch sizes", "Large batch sizes ensure time for built-in quality", "Large batch sizes increase variability"], correctIndex: 3 },
  { id: 10, question: "The analyzing step of the Portfolio Kanban system has a new Epic with a completed Lean business case. What is the next step?", options: ["It will be implemented once the Epic Owner approves the Lean business case", "It will be implemented if it has the highest WSJF ranking", "It will be moved to the Ready state in the Portfolio Kanban if it receives a \"go\" decision from Lean Portfolio Management", "It will remain in analysis until ART capacity exists"], correctIndex: 2 },
  { id: 11, question: "What are Sense Opportunity, Fund MVP, Pivot or Preserve and Deliver Value continuously?", options: ["Steps in the Business Agility Value Stream", "SAFe Lean-Agile Principles", "SAFe Core Values", "Flow Accelerators"], correctIndex: 0 },
  { id: 12, question: "What represents the workflow, activities, and automation needed to deliver new functionality more frequently?", options: ["The Continuous Delivery Pipeline", "The Portfolio Kanban", "The PI Planning process", "Lean Budget Guardrails"], correctIndex: 0 },
  { id: 13, question: "A SAFe Portfolio is a collection of what?", options: ["Solutions", "Functional teams", "Business units", "Development Value Streams"], correctIndex: 3 },
  { id: 14, question: "Who decides the Team PI Objective Business Value scoring after negotiation?", options: ["Business Owner", "Release Train Engineer", "Product Management", "Agile Team"], correctIndex: 0 },
  { id: 15, question: "What is used to brainstorm potential Portfolio future states?", options: ["KPIs and Lean budget guardrails", "Epics and Enablers", "SWOT and TOWS", "Enterprise business drivers"], correctIndex: 2 },
  { id: 16, question: "Which statement is a value from the Agile Manifesto?", options: ["Customer collaboration over contract negotiation", "Customer collaboration over feature negotiation", "Customer collaboration over internal conversations", "Customer collaboration over a constant indefinite pace"], correctIndex: 0 },
  { id: 17, question: "What is one key to leading a successful change?", options: ["Sustaining deceleration", "Generating long-term wins", "Instituting traditions", "Forming a strategic vision"], correctIndex: 3 },
  { id: 18, question: "What method provides a continuous understanding of the target market?", options: ["Design Thinking", "Participatory budgeting", "Lean Systems Engineering", "Lean Portfolio Management"], correctIndex: 0 },
  { id: 19, question: "A confidence vote is taken at the end of PI Planning. What best describes this process?", options: ["Managers vote", "Teams select delegates", "Business Owners vote", "Teams and the ART vote"], correctIndex: 3 },
  { id: 20, question: "Which statement applies to uncommitted objectives?", options: ["They can only receive business value of 3 or less", "They are included in the commitment", "They are items the team has high confidence in", "They are counted when calculating load"], correctIndex: 3 },
  { id: 21, question: "What is one of the Agile Release Train events?", options: ["Backlog refinement", "Product Owner sync", "Iteration Retrospective", "Solution Demo"], correctIndex: 3 },
  { id: 22, question: "Which activity supports relentless improvement?", options: ["Budget guardrails", "Inspect and Adapt", "Iteration planning", "Portfolio review"], correctIndex: 1 },
  { id: 23, question: "Which practice ensures alignment during PI execution?", options: ["Feature prioritization", "ART Sync", "Portfolio review", "WSJF"], correctIndex: 1 },
  { id: 24, question: "Which statement describes built-in quality?", options: ["Quality is inspected at the end", "Quality practices are integrated into development", "Quality is handled by QA teams", "Quality is measured only after release"], correctIndex: 1 },
  { id: 25, question: "What is the purpose of PI Planning?", options: ["Create budgets", "Align teams on a shared mission and plan", "Approve epics", "Define architecture"], correctIndex: 1 },
  { id: 26, question: "What type of thinking allows the Customer to pull value from the producer?", options: ["Design thinking", "Systems thinking", "Customer-centric thinking", "Lean thinking"], correctIndex: 3 },
  { id: 27, question: "Which role is responsible for maximizing the value of the ART backlog?", options: ["Release Train Engineer", "Product Management", "Scrum Master", "System Architect"], correctIndex: 1 },
  { id: 28, question: "How does SAFe describe Customer Centricity?", options: ["Practices to focus products on customers", "Market strategy", "A mindset focused on customer behaviors producing the best innovations", "Daily collaboration with customers"], correctIndex: 2 },
  { id: 29, question: "What helps ensure value delivery across Agile teams?", options: ["Team backlog refinement", "Agile Release Train", "Portfolio review", "Architecture board"], correctIndex: 1 },
  { id: 30, question: "What describes a cross-functional Agile team?", options: ["Delivers every 6 weeks", "Releases continuously", "Has no dependencies", "Optimized for communication and delivery of value"], correctIndex: 3 },
  { id: 31, question: "Which team provides processes and tools to support integration and validation?", options: ["Shared services", "DevOps team", "System Team", "Architecture team"], correctIndex: 2 },
  { id: 32, question: "What is one of the SAFe Core Values?", options: ["Lean-Agile Leadership", "Flow", "Culture", "Transparency"], correctIndex: 3 },
  { id: 33, question: "What ensures alignment across teams during PI execution?", options: ["Team stand-ups", "ART Sync", "Portfolio planning", "WSJF"], correctIndex: 1 },
  { id: 34, question: "What helps prioritize work economically?", options: ["Velocity", "WSJF", "Backlog refinement", "PI planning"], correctIndex: 1 },
  { id: 35, question: "What is one tool used in Design Thinking?", options: ["Portfolio canvas", "Set-based design", "Behavior-driven development", "Empathy maps"], correctIndex: 3 },
  { id: 36, question: "When basing decisions on economics, how are lead time, product cost, and development expense used?", options: ["Recover sunk costs", "Limit WIP", "Understand solution trade-offs", "Increase delivery speed"], correctIndex: 2 },
  { id: 37, question: "What is found on an ART planning board?", options: ["Features", "Tasks", "Epics", "User stories"], correctIndex: 0 },
  { id: 38, question: "What is an example of applying cadence and synchronization in SAFe?", options: ["Allocating budgets", "Conducting PI Planning", "Creating ARTs", "Using portfolio kanban"], correctIndex: 1 },
  { id: 39, question: "What is a benefit of separating deployment from release?", options: ["Reduce batch size", "Enable production testing", "Accelerate time to market", "Reduce delays"], correctIndex: 2 },
  { id: 40, question: "Which type of decision should remain centralized?", options: ["High cost of delay decisions", "Local information decisions", "Frequent decisions", "Decisions delivering large economic benefit"], correctIndex: 3 },
  { id: 41, question: "Who manages the Portfolio Kanban?", options: ["Solution Management", "Product Management", "Lean Portfolio Management", "Release Train Engineer"], correctIndex: 2 },
  { id: 42, question: "How do Lean-Agile leaders lead by example?", options: ["Using SAFe roadmap", "Implementing portfolio management", "Customer empathy", "Modeling the Lean-Agile mindset"], correctIndex: 3 },
  { id: 43, question: "Why do Business Owners assign business value to PI objectives?", options: ["Determine team priorities", "Override WSJF", "Avoid enablers", "Empower teams to make decisions"], correctIndex: 3 },
  { id: 44, question: "User business value and time criticality are components of what?", options: ["Story estimation", "Cost of Delay", "Acceptance criteria", "Product vision"], correctIndex: 1 },
  { id: 45, question: "Which SAFe Core Value includes use of \"common language\" and \"understand your customer\"?", options: ["Respect for people", "Alignment", "Transparency", "Relentless improvement"], correctIndex: 1 },
];
