/**
 * Public download path for each course brochure.
 *
 * Generated by scripts/build-brochures.ts — keep these in step with
 * BROCHURE_FILE there.
 */
export const COURSE_BROCHURE_HREF: Record<string, string> = {
  "product-owner-manager": "/brochures/AI-Empowered-SAFe-POPM-Brochure-Agile36.pdf",
  "leading-safe": "/brochures/AI-Empowered-Leading-SAFe-Brochure-Agile36.pdf",
  "scrum-master": "/brochures/AI-Empowered-SAFe-Scrum-Master-Brochure-Agile36.pdf",
  "advanced-scrum-master": "/brochures/AI-Empowered-SAFe-Advanced-Scrum-Master-Brochure-Agile36.pdf",
  "safe-for-teams": "/brochures/AI-Empowered-SAFe-for-Teams-Brochure-Agile36.pdf",
  "release-train-engineer": "/brochures/AI-Empowered-SAFe-RTE-Brochure-Agile36.pdf",
  "lean-portfolio-management": "/brochures/SAFe-Lean-Portfolio-Management-Brochure-Agile36.pdf",
  "agile-product-management": "/brochures/SAFe-Agile-Product-Management-Brochure-Agile36.pdf",
  "safe-for-architects": "/brochures/SAFe-for-Architects-Brochure-Agile36.pdf",
  devops: "/brochures/SAFe-DevOps-Brochure-Agile36.pdf",
  "value-stream-mapping": "/brochures/Value-Stream-Mapping-Brochure-Agile36.pdf",
  "responsible-ai": "/brochures/Responsible-AI-Brochure-Agile36.pdf",
  "ai-agent-builder": "/brochures/No-Code-AI-Agents-Automation-Brochure-Agile36.pdf",
  "ai-workflow-automation": "/brochures/AI-Workflow-Automation-Brochure-Agile36.pdf",
  "ai-app-builder": "/brochures/No-Code-AI-App-Builder-Brochure-Agile36.pdf",
  "generative-ai-project-managers": "/brochures/GenAI-for-Project-Managers-Brochure-Agile36.pdf",
  "certified-ai-product-manager": "/brochures/Certified-AI-Product-Manager-Brochure-Agile36.pdf",
  "certified-genai-practitioner": "/brochures/Certified-GenAI-Practitioner-Brochure-Agile36.pdf",
  "executive-genai-leadership": "/brochures/Executive-GenAI-Leadership-Brochure-Agile36.pdf",
  "ai-driven-scrum-master": "/brochures/AI-Driven-Scrum-Master-Brochure-Agile36.pdf",
};

export function brochureHrefFor(slug: string, fallback?: string): string | undefined {
  return COURSE_BROCHURE_HREF[slug] ?? fallback;
}
