/**
 * Public download path for each course brochure.
 *
 * Generated by scripts/build-brochures.ts — keep these in step with
 * BROCHURE_FILE there. Courses with no entry keep their legacy PDF.
 */
export const COURSE_BROCHURE_HREF: Record<string, string> = {
  "product-owner-manager": "/brochures/AI-Empowered-SAFe-POPM-Brochure-Agile36.pdf",
  "leading-safe": "/brochures/AI-Empowered-Leading-SAFe-Brochure-Agile36.pdf",
  "scrum-master": "/brochures/AI-Empowered-SAFe-Scrum-Master-Brochure-Agile36.pdf",
  "agile-product-management": "/brochures/SAFe-Agile-Product-Management-Brochure-Agile36.pdf",
  "safe-for-architects": "/brochures/SAFe-for-Architects-Brochure-Agile36.pdf",
  devops: "/brochures/SAFe-DevOps-Brochure-Agile36.pdf",
  "value-stream-mapping": "/brochures/Value-Stream-Mapping-Brochure-Agile36.pdf",
  "responsible-ai": "/brochures/Responsible-AI-Brochure-Agile36.pdf",
};

export function brochureHrefFor(slug: string, fallback?: string): string | undefined {
  return COURSE_BROCHURE_HREF[slug] ?? fallback;
}
