INSERT INTO course_schedules (
  course_name,
  course_slug,
  course_type,
  start_date,
  end_date,
  start_time,
  end_time,
  timezone,
  time_slot,
  format,
  duration,
  instructor_name,
  instructor_image,
  price,
  original_price,
  currency,
  seats_available,
  total_seats,
  language,
  exam_included,
  status,
  is_weekend,
  description
) VALUES 
(
  'No-Code AI Agents & Automation™',
  'ai-agent-builder',
  'No-Code AI Agents & Automation™',
  '2025-12-20 09:00:00-05:00',
  '2025-12-21 17:00:00-05:00',
  '09:00:00',
  '17:00:00',
  'America/New_York',
  'morning',
  'live-virtual',
  '2 Days',
  'Joe Puoci',
  '/Joe.jpeg',
  515.00,
  899.00,
  'USD',
  25,
  25,
  'English',
  true,
  'active',
  true,
  'Join our comprehensive No-Code AI Agents & Automation™ training. Learn to build, deploy, and manage AI agents effectively.'
),
(
  'SAFe Scrum Master',
  'scrum-master',
  'SAFe Scrum Master',
  '2025-12-20 09:00:00-05:00',
  '2025-12-21 17:00:00-05:00',
  '09:00:00',
  '17:00:00',
  'America/New_York',
  'morning',
  'live-virtual',
  '2 Days',
  'Joe Puoci',
  '/Joe.jpeg',
  515.00,
  899.00,
  'USD',
  25,
  25,
  'English',
  true,
  'active',
  true,
  'Master the SAFe Scrum Master framework. Learn to facilitate Agile teams and drive organizational agility.'
);
