/* Add SAFe Agile Product Management Aug 19-21, 2026 (Wed-Fri). Run in Supabase SQL Editor. */

INSERT INTO course_schedules (
  course_name,
  course_slug,
  course_type,
  start_date,
  end_date,
  start_time,
  end_time,
  timezone,
  format,
  duration,
  instructor_name,
  instructor_image,
  price,
  original_price,
  currency,
  total_seats,
  language,
  exam_included,
  status,
  is_weekend,
  hidden
) VALUES (
  'SAFe Agile Product Management',
  'agile-product-management',
  'SAFe',
  '2026-08-19 09:00:00-04:00',
  '2026-08-21 14:00:00-04:00',
  '09:00:00',
  '14:00:00',
  'America/New_York',
  'live-virtual',
  '03 days',
  'Joe Puoci',
  '/Joe.jpeg',
  1100.00,
  2200.00,
  'USD',
  25,
  'English',
  true,
  'active',
  false,
  false
);
