/* Add SAFe Lean Portfolio Management Jul 25-26 (Sat-Sun). Run in Supabase SQL Editor. */

INSERT INTO course_schedules (
  course_name,
  course_slug,
  course_type,
  start_date,
  end_date,
  start_time,
  end_time,
  timezone,
  time_slot,
  format,
  duration,
  instructor_name,
  instructor_image,
  price,
  original_price,
  currency,
  seats_available,
  total_seats,
  language,
  exam_included,
  status,
  is_weekend
) VALUES (
  'SAFe Lean Portfolio Management',
  'lean-portfolio-management',
  'SAFe LPM',
  '2026-07-25 09:00:00-04:00',
  '2026-07-26 17:00:00-04:00',
  '09:00:00',
  '17:00:00',
  'America/New_York',
  'morning',
  'live-virtual',
  '2 Days',
  'Deadra Stevenson',
  '/Deadra.jpeg',
  950.00,
  1900.00,
  'USD',
  15,
  20,
  'English',
  true,
  'active',
  true
);
