/* Add Advanced SAFe Scrum Master class Mar 12-13 (Thu-Fri). Run in Supabase SQL Editor. */

INSERT INTO course_schedules (
  course_name,
  course_slug,
  course_type,
  start_date,
  end_date,
  start_time,
  end_time,
  timezone,
  time_slot,
  format,
  duration,
  instructor_name,
  instructor_image,
  price,
  original_price,
  currency,
  seats_available,
  total_seats,
  language,
  exam_included,
  status,
  is_weekend
) VALUES (
  'SAFe Advanced Scrum Master',
  'advanced-scrum-master',
  'SAFe Scrum',
  '2026-03-12 09:00:00-04:00',
  '2026-03-13 14:00:00-04:00',
  '09:00:00',
  '14:00:00',
  'America/New_York',
  'morning',
  'live-virtual',
  '02 days',
  'Deadra Stevenson',
  '/Deadra.jpeg',
  950.00,
  1900.00,
  'USD',
  25,
  25,
  'English',
  true,
  'active',
  false
);
