/* Add Certified AI Product Manager class Feb 10-11. Run in Supabase SQL Editor. */

INSERT INTO course_schedules (
  course_name,
  course_slug,
  course_type,
  start_date,
  end_date,
  start_time,
  end_time,
  timezone,
  time_slot,
  format,
  duration,
  instructor_name,
  instructor_image,
  price,
  original_price,
  currency,
  seats_available,
  total_seats,
  language,
  exam_included,
  status
) VALUES (
  'Certified AI Product Manager™',
  'certified-ai-product-manager',
  'AI Product',
  '2026-02-10',
  '2026-02-11',
  '09:00:00',
  '14:00:00',
  'EST',
  'morning',
  'live-virtual',
  '02 days',
  'Joe Puoci',
  '/Joe.jpeg',
  400.00,
  800.00,
  'USD',
  25,
  25,
  'English',
  true,
  'active'
);
