/* Add SAFe Scrum Master class Mar 14-15 (Sat-Sun). Run in Supabase SQL Editor. */

INSERT INTO course_schedules (
  course_name,
  course_slug,
  course_type,
  start_date,
  end_date,
  start_time,
  end_time,
  timezone,
  time_slot,
  format,
  duration,
  instructor_name,
  instructor_image,
  price,
  original_price,
  currency,
  seats_available,
  total_seats,
  language,
  exam_included,
  status,
  is_weekend
) VALUES (
  'SAFe Scrum Master',
  'scrum-master',
  'SAFe',
  '2026-03-14 09:00:00-04:00',
  '2026-03-15 14:00:00-04:00',
  '09:00:00',
  '14:00:00',
  'America/New_York',
  'morning',
  'live-virtual',
  '02 days',
  'Deadra Stevenson',
  '/Deadra.jpeg',
  555.00,
  1110.00,
  'USD',
  25,
  25,
  'English',
  true,
  'active',
  true
);
