/* Add SAFe DevOps Mar 10-11 (Joe Puoci) and Lean Portfolio Management Mar 7-8 (Sat-Sun). Run in Supabase SQL Editor. */

-- 1) SAFe DevOps Mar 10-11 (Tue-Wed), Joe Puoci
INSERT INTO course_schedules (
  course_name,
  course_slug,
  course_type,
  start_date,
  end_date,
  start_time,
  end_time,
  timezone,
  time_slot,
  format,
  duration,
  instructor_name,
  instructor_image,
  price,
  original_price,
  currency,
  seats_available,
  total_seats,
  language,
  exam_included,
  status,
  is_weekend
) VALUES (
  'SAFe DevOps',
  'devops',
  'SAFe',
  '2026-03-10 09:00:00-04:00',
  '2026-03-11 14:00:00-04:00',
  '09:00:00',
  '14:00:00',
  'America/New_York',
  'morning',
  'live-virtual',
  '02 days',
  'Joe Puoci',
  '/Joe.jpeg',
  699.00,
  1398.00,
  'USD',
  25,
  25,
  'English',
  true,
  'active',
  false
);

-- 2) Lean Portfolio Management Mar 7-8 (Sat-Sun)
INSERT INTO course_schedules (
  course_name,
  course_slug,
  course_type,
  start_date,
  end_date,
  start_time,
  end_time,
  timezone,
  time_slot,
  format,
  duration,
  instructor_name,
  instructor_image,
  price,
  original_price,
  currency,
  seats_available,
  total_seats,
  language,
  exam_included,
  status,
  is_weekend
) VALUES (
  'SAFe Lean Portfolio Management',
  'lean-portfolio-management',
  'SAFe',
  '2026-03-07 09:00:00-04:00',
  '2026-03-08 14:00:00-04:00',
  '09:00:00',
  '14:00:00',
  'America/New_York',
  'morning',
  'live-virtual',
  '02 days',
  'Deadra Stevenson',
  '/Deadra.jpeg',
  1095.00,
  2190.00,
  'USD',
  25,
  25,
  'English',
  true,
  'active',
  true
);
