/* Add SAFe Agile Product Management class Feb 25-27 (Wed-Thu-Fri). Run in Supabase SQL Editor. */

INSERT INTO course_schedules (
  course_name,
  course_slug,
  course_type,
  start_date,
  end_date,
  start_time,
  end_time,
  timezone,
  time_slot,
  format,
  duration,
  instructor_name,
  instructor_image,
  price,
  original_price,
  currency,
  seats_available,
  total_seats,
  language,
  exam_included,
  status,
  is_weekend
) VALUES (
  'SAFe Agile Product Management',
  'agile-product-management',
  'SAFe APM',
  '2026-02-25 09:00:00-05:00',
  '2026-02-27 14:00:00-05:00',
  '09:00:00',
  '14:00:00',
  'America/New_York',
  'morning',
  'live-virtual',
  '03 days',
  'Deadra Stevenson',
  '/Deadra.jpeg',
  1095.00,
  2190.00,
  'USD',
  25,
  25,
  'English',
  true,
  'active',
  false
);
