INSERT INTO course_schedules (
  course_name,
  course_slug,
  course_type,
  start_date,
  end_date,
  start_time,
  end_time,
  timezone,
  time_slot,
  format,
  duration,
  instructor_name,
  instructor_image,
  price,
  original_price,
  currency,
  seats_available,
  total_seats,
  language,
  exam_included,
  status,
  is_weekend
)
VALUES (
  'Certified AI Product Manager™',
  'certified-ai-product-manager',
  'AI Product',
  '2026-02-21 09:00:00-05:00',
  '2026-02-22 14:00:00-05:00',
  '09:00:00',
  '14:00:00',
  'America/New_York',
  'morning',
  'live-virtual',
  '02 days',
  'Deadra Stevenson',
  '/Deadra.jpeg',
  400.00,
  800.00,
  'USD',
  25,
  25,
  'English',
  true,
  'active',
  true
)
ON CONFLICT DO NOTHING;
