export type LpmQuestion = {
  id: number;
  question: string;
  options: string[];
  correctIndex: number;
};

export const LPM_QUESTIONS: LpmQuestion[] = [
  { id: 1, question: "What is one major field of an epic hypothesis statement?", options: ["Leading Indicators", "Solution hypothesis", "Cost Structure"], correctIndex: 0 },
  { id: 2, question: "OKR's help support which two core values?", options: ["Respect for people and transparency", "Transparency and alignment", "Alignment and Respect for People"], correctIndex: 1 },
  { id: 3, question: "What support does reviewing and validating portfolio Kanban WIP limits provide?", options: ["Coordination", "Vision", "Flow"], correctIndex: 2 },
  { id: 4, question: "What is an epic owner responsible for?", options: ["Collaborating with agile teams to build MVP", "Making go/no go decisions", "Sizing epics"], correctIndex: 0 },
  { id: 5, question: "Which of the following is a component of cost of delay?", options: ["ROI", "Time criticality", "Utilization"], correctIndex: 1 },
  { id: 6, question: "What is a responsibility of the VMO?", options: ["Fostering agile contracts and partnerships", "Directing the LACE", "Centralized funding for tooling and coaching"], correctIndex: 0 },
  { id: 7, question: "Which of the following is a Lean Thinking Principle?", options: ["Sequence jobs for maximum benefit", "Deliver working software", "Identify value stream for product"], correctIndex: 2 },
  { id: 8, question: "How does SAFe ensure organizations can budget MVP costs?", options: ["By budgeting the value streams", "By budgeting an estimated investment to validate the epic hypothesis", "By budgeting the full anticipated implementation costs"], correctIndex: 1 },
  { id: 9, question: "What is a key responsibility of agile portfolio operations?", options: ["They support program execution", "To establish program flow", "To establish portfolio flow"], correctIndex: 0 },
  { id: 10, question: "What influences how we sequence epics and enablers on the portfolio roadmap?", options: ["Market rhythms", "PI objectives", "Canvas"], correctIndex: 0 },
  { id: 11, question: "What is an example of a pivot?", options: ["Hypothesis is false, need new experiments", "Hypothesis is true, stop work", "Hypothesis is false, we have no problems to solve"], correctIndex: 0 },
  { id: 12, question: "What is one way to demonstrate a lean and agile mindset?", options: ["By eliminating waste", "Command and Control", "By implementing agile methodologies within teams"], correctIndex: 0 },
  { id: 13, question: "What statement is true about Agile contracts?", options: ["They benefit both parties", "All details must be known upfront", "The program, scope, cost are variable"], correctIndex: 0 },
  { id: 14, question: "What is true about strategic themes?", options: ["They are derived from OKR's", "They link the portfolio to the enterprise strategy", "They connect multiple value streams to the enterprise"], correctIndex: 1 },
  { id: 15, question: "What is achieved by establishing guardrails?", options: ["To describe budgetary, governance, and spending practices for the portfolio", "To make strategic decisions", "To provide estimates for epics"], correctIndex: 0 },
  { id: 16, question: "How do we maintain compliance?", options: ["Build solutions incrementally", "Build compliance requirements during PI planning", "Identify compliance NFR's in the Epic Hypothesis Statement"], correctIndex: 2 },
  { id: 17, question: "What is critical for using WSJF with Enablers?", options: ["Decreasing value", "Increased risk of sequencing items incorrectly", "Increased time"], correctIndex: 1 },
  { id: 18, question: "Responsibility of an APMO?", options: ["Fostering Agile Contracts", "Facilitating Team Ceremonies"], correctIndex: 0 },
  { id: 19, question: "What is an advantage of LPM over traditional budgeting?", options: ["Provides effective financial control over investments with less overhead", "Increases ability to budget the roadmap", "Transparency"], correctIndex: 0 },
  { id: 20, question: "Which two people have the greatest influence over developing strategic themes?", options: ["Epic owners and Scrum Masters", "APMO and LACE", "Business owners and Enterprise Executives"], correctIndex: 2 },
  { id: 21, question: "What should be coordinated within a value stream?", options: ["Internal and external suppliers", "Capabilities", "Systems Team"], correctIndex: 0 },
  { id: 22, question: "Why would a single portfolio create multiple portfolio canvases?", options: ["To explore multiple future states", "To analyze work", "To account for different value streams"], correctIndex: 0 },
  { id: 23, question: "What is an advantage of funding value streams?", options: ["Easier to get budget approved if a feature is taking longer than expected", "Easier to forecast expenses", "Easier to track cost of projects"], correctIndex: 1 },
  { id: 24, question: "What are two economic tradeoff parameters?", options: ["Cycle time, lead time", "ROI, cost of delay", "Lead time, development expense"], correctIndex: 2 },
  { id: 25, question: "Why is it necessary to have business owner engagement?", options: ["To ensure that capacity allocation is followed", "To determine metrics for the ART", "To ensure priorities are aligned with the portfolio objectives"], correctIndex: 2 },
  { id: 26, question: "What statement is true about identifying opportunities with a SWOT analysis?", options: ["Understanding the current state of your value stream, product, or portfolio", "It identifies strategic outcomes for the future", "Helps to identify strategic themes"], correctIndex: 0 },
  { id: 27, question: "What is the purpose of sequencing epics using WSJF?", options: ["To improve economic outcomes for the portfolio", "To generate estimates for implementation", "To prioritize items that will provide business context"], correctIndex: 0 },
  { id: 28, question: "What is an example of how capacity allocation is used as a Lean budget guardrail?", options: ["Allocating 20% of an ART to a new ART for the current program increment", "Allocating 30% of total Agile release train capacity towards infrastructure", "Allocating 100% of a PO's capacity to one team on a particular ART"], correctIndex: 1 },
  { id: 29, question: "In what state of the portfolio Kanban may an ART need to reserve capacity?", options: ["Implementing", "Funnel", "Portfolio Backlog"], correctIndex: 0 },
  { id: 30, question: "What input helps inform an evolving enterprise strategy?", options: ["Portfolio Canvas", "Strategic Themes", "OKR's"], correctIndex: 0 },
  { id: 31, question: "What is a relevant aspect to consider when developing a portfolio roadmap?", options: ["There is less clarity as the time horizon extends", "Evaluate KPI's", "Integrating program capacity allocation"], correctIndex: 0 },
  { id: 32, question: "What statement is true about value stream KPI's?", options: ["Measure how a value stream performs against forecasted business outcomes", "They are formulated using OKR's", "Close feedback loop"], correctIndex: 0 },
  { id: 33, question: "What guardrail ensures that the future is not starved while over investing in today?", options: ["Investment horizons", "Continuous Business Owner Engagement", "Capacity Allocation"], correctIndex: 0 },
  { id: 34, question: "When is it appropriate to have a centralized LACE?", options: ["When a small or medium company has a single portfolio", "When there are core practices that need to be shared", "When cross business units need to collaborate"], correctIndex: 0 },
  { id: 35, question: "What is the focus of the APMO?", options: ["Coordinating epic execution", "Supporting program execution", "Setting up the portfolio kanban"], correctIndex: 1 },
  { id: 36, question: "Why must value stream budgets be adjusted over time?", options: ["To take advantage of emerging opportunities", "To support rolling wave planning", "Maximize ROI"], correctIndex: 0 },
  { id: 37, question: "During what state of the portfolio Kanban does MVP get created?", options: ["Analyzing", "Funnel", "Implementing"], correctIndex: 0 },
  { id: 38, question: "What must an enterprise do to organize the portfolio around value?", options: ["Move from projects to products and services", "Organize ARTs by platforms or components", "Organize ARTs by function"], correctIndex: 0 },
  { id: 39, question: "What are two characteristics of the portfolio Kanban?", options: ["Epics are pulled across the board as capacity allows, WIP limits promote flow; Go/No go decisions are required at the funnel and the analyzing state", "The Kanban reflects the capacity and when work will be completed"], correctIndex: 0 },
  { id: 40, question: "Many companies release products during periods of consumer demand. This is an example of what?", options: ["Market rhythm", "Develop on cadence", "Portfolio synchronization"], correctIndex: 0 },
  { id: 41, question: "In addition to alignment, the strategic portfolio review is designated to create what?", options: ["Investment guidance with decentralized decision making", "Operational delivery", "Decision awareness"], correctIndex: 0 },
  { id: 42, question: "What statement is true about the portfolio roadmap?", options: ["It indicates the interaction across value streams", "It's a high level view of work", "It forecasts future work that is in alignment with the PI"], correctIndex: 0 },
  { id: 43, question: "What is adjusted after participatory budgeting is finished?", options: ["Epic budgets", "Lean Budget guardrails", "Value Stream Budgets"], correctIndex: 2 },
  { id: 44, question: "Benefits are realized when ARTs within a value stream are aligned to what?", options: ["A common cadence", "The same portfolio guardrails", "The same epic owner"], correctIndex: 0 },
  { id: 45, question: "What metric is used to measure portfolio performance?", options: ["OKR's", "Program predictability", "Value Stream KPI's"], correctIndex: 0 },
  { id: 46, question: "When is an epic considered done in the portfolio Kanban?", options: ["LPM has determined that no further governance is required", "When it's time to pivot", "When the epic hypothesis has been proven"], correctIndex: 0 },
  { id: 47, question: "What is the primary outcome of participatory budgeting?", options: ["Investment in horizons", "Value stream funding adjustments", "Investment in capabilities"], correctIndex: 1 },
  { id: 48, question: "What two activities occur when an epic is in the analyzing state?", options: ["Discover and build MVP", "Refine WSJF, Create Lean Business Case", "Define and refine the epic hypothesis statement"], correctIndex: 1 },
  { id: 49, question: "What is the purpose of MVP for an epic?", options: ["To avoid creating an epic that has no value", "To prove a business outcome hypothesis", "Build and deliver solutions"], correctIndex: 1 },
  { id: 50, question: "What are the three essential collaborations the LPM function provides?", options: ["Strategy & Investment Funding, Portfolio Operations, Lean Governance", "Daily Standup, Iteration Planning, Backlog Grooming", "Portfolio Sync, Strategic Portfolio Review, Participatory Budgeting"], correctIndex: 0 },
  { id: 51, question: "What are three disadvantages to project cost accounting?", options: ["Simple, agile, and responsive to change", "Funding products, services, and solutions", "Multiple cost centers, complex budgeting process, utilized based planning"], correctIndex: 2 },
];
